
# my_controllers.yaml
controller_manager:
  ros__parameters:
    update_rate: 100.0  # Update rate for the controller manager
    use_sim_time: true   # Use simulation time

# Controller for differential drive
diff_drive_controller:
  ros__parameters:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel: "left_wheel_joint"
    right_wheel: "right_wheel_joint"
    wheel_separation: 0.5  # Distance between the wheels
    wheel_radius: 0.1      # Radius of the wheels
    cmd_vel_timeout: 0.5   # Command velocity timeout
    publish_rate: 50.0     # Rate at which to publish the odometry

# Joint state broadcaster
joint_state_broadcaster:
  ros__parameters:
    type: "joint_state_broadcaster/JointStateBroadcaster"
    update_rate: 100.0     # Rate to update joint states
